plugins {
    id 'java'
}

group = 'com.ureca'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':ii-common')
    implementation project(':ii-domain')
    implementation project(':ii-infrastructure')
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    // thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    // jackson (to json)
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    // rabbit MQ
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.session:spring-session-data-redis'
    // redis
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    // spring-batch
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    // S3
    implementation 'com.amazonaws:aws-java-sdk-s3:1.12.300'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'
    // Spring Actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // Prometheus
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    // Excel
    implementation 'org.apache.poi:poi-ooxml:5.2.3'
    implementation 'org.apache.poi:poi:5.2.3'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'org.apache.xmlbeans:xmlbeans:5.1.1'
    implementation 'org.apache.commons:commons-compress:1.21'
}

jar {
    enabled = false
}

test {
    useJUnitPlatform()
}